/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-primary-fixed-variant': '#5c4300',
        'inverse-surface': '#2e3132',
        'surface-container-highest': '#e1e3e4',
        'secondary-fixed': '#d4e5ef',
        'surface-container-high': '#e7e8e9',
        'outline-variant': '#d3c5ad',
        'on-secondary-fixed-variant': '#394951',
        primary: '#795900',
        tertiary: '#5f5f4f',
        'on-tertiary-fixed': '#1c1c0f',
        'error-container': '#ffdad6',
        'tertiary-fixed': '#e5e3ce',
        'on-secondary-container': '#55656d',
        'surface-bright': '#f8f9fa',
        'tertiary-fixed-dim': '#c9c7b3',
        'inverse-primary': '#f8bd2a',
        secondary: '#506169',
        'primary-fixed-dim': '#f8bd2a',
        background: '#f8f9fa',
        'surface-container-lowest': '#ffffff',
        'on-background': '#191c1d',
        'on-error': '#ffffff',
        'on-primary-fixed': '#261a00',
        'surface-container-low': '#f3f4f5',
        'on-surface-variant': '#4f4633',
        'on-tertiary-container': '#555545',
        'surface-container': '#edeeef',
        'on-surface': '#191c1d',
        'on-tertiary-fixed-variant': '#474838',
        'primary-container': '#fbc02d',
        surface: '#f8f9fa',
        'on-tertiary': '#ffffff',
        'inverse-on-surface': '#f0f1f2',
        'on-error-container': '#93000a',
        'surface-dim': '#d9dadb',
        'secondary-fixed-dim': '#b8c9d3',
        outline: '#817661',
        error: '#ba1a1a',
        'on-primary': '#ffffff',
        'primary-fixed': '#ffdfa0',
        'on-secondary-fixed': '#0d1e25',
        'secondary-container': '#d1e2ec',
        'on-secondary': '#ffffff',
        'surface-tint': '#795900',
        'surface-variant': '#e1e3e4',
        'on-primary-container': '#6c5000',
        'tertiary-container': '#cbcab5',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        md: '24px',
        lg: '48px',
        xl: '64px',
        'margin-desktop': '40px',
        xs: '4px',
        'margin-mobile': '16px',
        base: '8px',
        sm: '12px',
        gutter: '20px',
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-bold': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
        'label-md': ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
}
